// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.1
// source: internal/signerpb/signer.proto

package signerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier. The implementation maps it to a backend-specific key.
	KeyRef        string `protobuf:"bytes,1,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_internal_signerpb_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signerpb_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_signerpb_signer_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublicKeyRequest) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

type GetPublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DER-encoded SubjectPublicKeyInfo.
	PublicKeyDer []byte `protobuf:"bytes,1,opt,name=public_key_der,json=publicKeyDer,proto3" json:"public_key_der,omitempty"`
	// JWS algorithm name: RS256, PS256, ES256 or ES384.
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Optional DER-encoded X.509 certificate.
	CertificateDer []byte `protobuf:"bytes,3,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	// Backend-specific key version identifier, for logging and drift detection.
	KeyVersion    string `protobuf:"bytes,4,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_internal_signerpb_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signerpb_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_signerpb_signer_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicKeyResponse) GetPublicKeyDer() []byte {
	if x != nil {
		return x.PublicKeyDer
	}
	return nil
}

func (x *GetPublicKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GetPublicKeyResponse) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *GetPublicKeyResponse) GetKeyVersion() string {
	if x != nil {
		return x.KeyVersion
	}
	return ""
}

type SignRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	KeyRef string                 `protobuf:"bytes,1,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	// Hash of the signing input, computed by the caller. Length must match the
	// hash implied by algorithm: 32 bytes for SHA-256, 48 for SHA-384.
	Digest []byte `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	// JWS algorithm name; also selects the padding scheme.
	Algorithm     string `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_internal_signerpb_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signerpb_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_internal_signerpb_signer_proto_rawDescGZIP(), []int{2}
}

func (x *SignRequest) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

func (x *SignRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *SignRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type SignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signature in JWS wire form, ready to base64url-encode: PKCS#1 v1.5 or PSS
	// for RSA, and raw R||S concatenation (not DER) for ECDSA.
	Signature     []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	KeyVersion    string `protobuf:"bytes,2,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_internal_signerpb_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signerpb_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_internal_signerpb_signer_proto_rawDescGZIP(), []int{3}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignResponse) GetKeyVersion() string {
	if x != nil {
		return x.KeyVersion
	}
	return ""
}

var File_internal_signerpb_signer_proto protoreflect.FileDescriptor

const file_internal_signerpb_signer_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/signerpb/signer.proto\x12\ruaa.signer.v1\".\n" +
	"\x13GetPublicKeyRequest\x12\x17\n" +
	"\akey_ref\x18\x01 \x01(\tR\x06keyRef\"\xa4\x01\n" +
	"\x14GetPublicKeyResponse\x12$\n" +
	"\x0epublic_key_der\x18\x01 \x01(\fR\fpublicKeyDer\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12'\n" +
	"\x0fcertificate_der\x18\x03 \x01(\fR\x0ecertificateDer\x12\x1f\n" +
	"\vkey_version\x18\x04 \x01(\tR\n" +
	"keyVersion\"\\\n" +
	"\vSignRequest\x12\x17\n" +
	"\akey_ref\x18\x01 \x01(\tR\x06keyRef\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\"M\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1f\n" +
	"\vkey_version\x18\x02 \x01(\tR\n" +
	"keyVersion2\xaa\x01\n" +
	"\x0eSigningService\x12W\n" +
	"\fGetPublicKey\x12\".uaa.signer.v1.GetPublicKeyRequest\x1a#.uaa.signer.v1.GetPublicKeyResponse\x12?\n" +
	"\x04Sign\x12\x1a.uaa.signer.v1.SignRequest\x1a\x1b.uaa.signer.v1.SignResponseBU\n" +
	"-org.cloudfoundry.identity.uaa.oauth.signer.v1P\x01Z\"acceptance_tests/internal/signerpbb\x06proto3"

var (
	file_internal_signerpb_signer_proto_rawDescOnce sync.Once
	file_internal_signerpb_signer_proto_rawDescData []byte
)

func file_internal_signerpb_signer_proto_rawDescGZIP() []byte {
	file_internal_signerpb_signer_proto_rawDescOnce.Do(func() {
		file_internal_signerpb_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_signerpb_signer_proto_rawDesc), len(file_internal_signerpb_signer_proto_rawDesc)))
	})
	return file_internal_signerpb_signer_proto_rawDescData
}

var file_internal_signerpb_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_signerpb_signer_proto_goTypes = []any{
	(*GetPublicKeyRequest)(nil),  // 0: uaa.signer.v1.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil), // 1: uaa.signer.v1.GetPublicKeyResponse
	(*SignRequest)(nil),          // 2: uaa.signer.v1.SignRequest
	(*SignResponse)(nil),         // 3: uaa.signer.v1.SignResponse
}
var file_internal_signerpb_signer_proto_depIdxs = []int32{
	0, // 0: uaa.signer.v1.SigningService.GetPublicKey:input_type -> uaa.signer.v1.GetPublicKeyRequest
	2, // 1: uaa.signer.v1.SigningService.Sign:input_type -> uaa.signer.v1.SignRequest
	1, // 2: uaa.signer.v1.SigningService.GetPublicKey:output_type -> uaa.signer.v1.GetPublicKeyResponse
	3, // 3: uaa.signer.v1.SigningService.Sign:output_type -> uaa.signer.v1.SignResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_signerpb_signer_proto_init() }
func file_internal_signerpb_signer_proto_init() {
	if File_internal_signerpb_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_signerpb_signer_proto_rawDesc), len(file_internal_signerpb_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_signerpb_signer_proto_goTypes,
		DependencyIndexes: file_internal_signerpb_signer_proto_depIdxs,
		MessageInfos:      file_internal_signerpb_signer_proto_msgTypes,
	}.Build()
	File_internal_signerpb_signer_proto = out.File
	file_internal_signerpb_signer_proto_goTypes = nil
	file_internal_signerpb_signer_proto_depIdxs = nil
}
